# Generated by Django 4.0.2 on 2022-02-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Título da categoria')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Imagem')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Thumbnail')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastramento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
                'ordering': ('-date_added',),
            },
        ),
    ]
